# Site settings
name: Huzaifa
title: Huzaifa
description: A sharp-minded, detail oriented final year CSE UnderGrad at IIITN passionate about working on softwares.
url: https://brittanychiang.com
baseurl: ""
email: huzaifa060200@gmail.com
cover: https://brittanychiang.com/img/og.png
logo: https://raw.githubusercontent.com/huzaifa06/huzaifa06.github.io/main/49772-200.png
resume: https://drive.google.com/file/d/1SmDDhzN7j4mXNO_zRaZkRTdPlaJ1HUBx/view?usp=sharing
social:
  - title: email
    url: mailto:huzaifa060200@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/huzaifa06
  - title: instagram
    url: https://instagram.com/huz.aifa.3007
  - title: github
    url: https://github.com/huzaifa06

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
